SUPABASE_URL = "https://apuavcvwnfwvdoetnekc.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwdWF2Y3Z3bmZ3dmRvZXRuZWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTAwOTQsImV4cCI6MjA3Mjg4NjA5NH0.ryYDYSclXBxsRiyzWUsd_otL7ppvlJ8OryeRH-SdNo4"
